#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Do damBreak
#(cd damBreak && foamRunTutorials)

# Clone case
# cloneCase damBreak damBreakFine
m4 system/blockMeshdict.m4 >system/blockMeshDict 

#(
    #cd damBreakFine || exit

    # Modify case
    #setDamBreakFine
    restore0Dir
    #cp 0/alpha.water.orig 0/alpha.water
    # And execute
    runApplication blockMesh
    #runApplication topoSet
    runApplication setFields
    # runApplication decomposePar
    # runParallel $(getApplication)
    runApplication $(getApplication)
    # runApplication reconstructPar
#)

#------------------------------------------------------------------------------
